apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcsampleconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PCSampleconfig
  template:
    metadata:
      labels:
        app: PCSampleconfig
    spec:
      containers:
      - name: pcsamplerepos
        image: 848843dnazureacr.azurecr.io/pcsamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: pcsampleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PCSampleconfig